--Lock with kill command
SET LINES 300 PAGES 100
COL USERNAME FOR A25
COL SPID FOR 999999
COL OSUSER FOR A20
COL LOGON_TIME FOR A25
COL BLOQUEADOR FOR A60
COL SESSAO FOR A20
SELECT SUBSTR(DECODE(L.REQUEST,0,'BLOQUEADOR: ','BLOQUEADO: ')||L.SID,1,20) SESSAO,
S.USERNAME,
S.SID,
S.SERIAL#,
B.SPID,
S.STATUS,
S.OSUSER,
S.MACHINE,
S.PROGRAM,
L.ID1,
L.ID2,
L.LMODE,
L.REQUEST,
L.TYPE,
L.INST_ID INSTANCE,
TO_CHAR(S.LOGON_TIME,'DD-MM-RR HH24:MI:SS') LOGON_TIME,
'ALTER SYSTEM KILL SESSION ''' || S.SID || ',' || S.SERIAL# || ',@'||L.INST_ID||''' IMMEDIATE;' BLOQUEADOR
FROM
GV$LOCK L,
GV$SESSION S,
V$PROCESS B
WHERE S.PADDR=B.ADDR
AND S.SID=L.SID
AND (L.ID1, L.ID2, L.TYPE) IN
(SELECT L.ID1, L.ID2, L.TYPE FROM GV$LOCK L WHERE L.REQUEST>0)
ORDER BY SESSAO, L.REQUEST;

