SET LINES 400 
SET PAGES 100
COL DESTINATION FORMAT A40
COL DEST_NAME FORMAT A40
COL STATUS FORMAT A15
COL INST FORMAT 99
SELECT DEST_NAME, INST_ID INST, DESTINATION, STATUS, ERROR 
FROM GV$ARCHIVE_DEST 
WHERE DESTINATION IS NOT NULL ORDER BY 1,2;